baseURL = "http://centiservices.com/"
languageCode = "en-us"
title = "Centiservices"
theme = "detox"
publishDir = "docs"

[params]
  author = "Colin Jones"
  twitter_name = "trptcolin"
  github = "trptcolin/centiservices"
  description = "10,000 times better than microservices"
