baseURL = "https://centiservices.com/"
languageCode = "en-us"
title = "Centiservices"
theme = "detox"
publishDir = "public"

[params]
  author = "Colin Jones"
  twitter_name = "trptcolin"
  github = "trptcolin/centiservices"
  description = "10,000x better than microservices"
